# Fuego contra Fuego

Instalamos, cargamos y seteamos el entorno

In [10]:
%pip install optuna

Requirement already satisfied: optuna in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (1.19.1)
Requirement already satisfied: colorlog in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (4.70.0)
Requirement already satisfied: PyYAML in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (1.4.1)
Requirement already satisfied: typing-extensions>=4.12 in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/.venv/lib/python3.14/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from tqdm.notebook import tqdm

from sklearn.tree import DecisionTreeClassifier, plot_tree,  _tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import ShuffleSplit, StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

from joblib import Parallel, delayed

import optuna
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_slice, plot_contour

from time import time

import pickle

In [12]:
from pathlib import Path

project_path = Path('/Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026')
dataset_dir = project_path / 'data'
modelos_dir = project_path / 'modelos'
modelos_dir.mkdir(parents=True, exist_ok=True)
dataset_path = dataset_dir.as_posix() + '/'
modelos_path = modelos_dir.as_posix() + '/'
db_path = dataset_path
dataset_file = 'competencia_01.csv'
dataset_file_path = dataset_dir / dataset_file
if not dataset_file_path.is_file():
    raise FileNotFoundError(f'No se encontró el dataset local: {dataset_file_path}')
print(f'Cargando dataset local: {dataset_file_path}')

ganancia_acierto = 1_072_500
costo_estimulo = 27_500

mes_train = 202103
mes_test = 202105

# agregue sus semillas
semilla = 17
semillas = np.random.choice(1000000, size=50, replace=False).tolist()

data = pd.read_csv(dataset_file_path)

Cargando dataset local: /Users/thenseler/Documents/Maestria/DMEyF/dmeyf2026/data/competencia_01.csv

Seguimos trabajando con Marzo como entrenamiento y Mayo como test.

In [13]:
X = data[data['foto_mes'] == mes_train]
y = X['clase_ternaria']
X = X.drop(columns=['clase_ternaria'])

In [14]:
X_futuro = data[data['foto_mes'] == mes_test]
y_futuro = X_futuro['clase_ternaria']
X_futuro = X_futuro.drop(columns=['clase_ternaria'])

Y variaremos la forma de la función de ganancia, para poder ser utilizada de una forma más genérica.

In [16]:
def ganancia_prob(y_hat, y, prop=1, class_index=1, threshold=0.025):
  @np.vectorize
  def ganancia_row(predicted, actual, threshold=0.025):
    return  (predicted >= threshold) * (ganancia_acierto if actual == "BAJA+2" else -costo_estimulo)

  return ganancia_row(y_hat[:,class_index], y).sum() / prop

Entrenemos y recordemos cuanto nos daba la ganancia en **Mayo**

Hablemos de ensemables, qué son?

* Un ensemble de modelos es una técnica donde se combinan múltiples modelos individuales para mejorar la precisión y robustez de las predicciones. La idea es que al combinar varios modelos, se pueden aprovechar las fortalezas de cada uno y reducir la posibilidad de errores que podría cometer un único modelo.

**Tipos de ensemble**:
 * **Bagging (Bootstrap Aggregating)**: Consiste en entrenar varios modelos base en diferentes subconjuntos del conjunto de datos de entrenamiento obtenidos mediante técnicas de remuestreo como el bootstrap y luego promediar sus predicciones. Ejemplo: **Random Forest**
 * **Boosting**: En esta técnica, los modelos se entrenan de manera secuencial. Cada modelo intenta corregir los errores cometidos por el modelo anterior. Ejemplo: AdaBoost y **Gradient Boosting**.
 * **Stacking**: En el stacking, se entrenan varios modelos y se combinan usando un "modelo meta". Las predicciones de los modelos base sirven como features para entrenar este modelo meta, que produce la predicción final.

* **Ventajas de usar ensemble de modelos**:
 * **Mejor rendimiento**: Al combinar modelos, generalmente se mejora la precisión en comparación con un solo modelo.
 * **Robustez**: Al integrar diferentes modelos, se mitiga el riesgo de que los errores de un modelo individual afecten gravemente la predicción final.

Pongamos foco en el **Random Forest**

Es un algoritmo de aprendizaje automático que funciona creando un conjunto de árboles de decisión. Para la creación de **árboles distintos** utiliza una técnica llamada bagging para crear múltiples subconjuntos del conjunto de datos de entrenamiento. Cada subconjunto se genera seleccionando al azar muestras del conjunto de datos original con reemplazo. No usa la totalidad de los datos de entrenamiento para cada conjunto. Los datos que quedan fueran son conocidos como **Out of Bag (oob)**

Para cada subconjunto, se construye un árbol de decisión. Sin embargo en cada nodo del árbol, **Random Forest** selecciona de forma aleatoria un grupo de variables y ajusta el árbol con esas variables. Este proceso ayuda a crear árboles que son menos correlacionados entre sí.

Cada árbol en el bosque se entrena de manera independiente usando su respectivo subconjunto de datos. Lueago, para una nueva observación, cada árbol realiza una predicción. El Random Forest luego combina las predicciones de todos los árboles para hacer una predicción final, devolviendo el promedio de las probabilidades de cada árbol individual.

Como desde la clase pasada solo personas más inteligentes, no vamos a empezar a probar **Random Forest** simples. Vamos a parametrizarlo desde el vamos.

Primero vamos a entender algunas limitaciones de la implementación:

El **Random Forest** no soporta nulos! Shame on you sklearn!.

Vamos a tener que imputar los datos. Discutamos entre todos forma de imputar los datos, mientras para salir del paso usamos la peor de todas.

In [17]:
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
Xi = imp_median.fit_transform(X)
Xif = imp_median.fit_transform(X_futuro)

Los parámetros que se pueden ajustar en el **rf** son

1. **n_estimators**: Número de árboles en el bosque.
2. **max_depth**: Profundidad máxima de los árboles.
3. **min_samples_split**: Número mínimo de muestras requeridas para dividir un nodo interno.
4. **min_samples_leaf**: Número mínimo de muestras requeridas para estar en un nodo hoja.
5. **max_features**: Número de features a usar en cada árbol. **sqrt** es una elección histórica.
6. **max_leaf_nodes**: Número máximo de nodos hoja en cada árbol.
7. **oob_score**: Indica si se usa la muestra fuera de bolsa (out-of-bag) para estimar la calidad del modelo. Para evitar hacer un **montecarlo-cross-validation** que se toma su tiempo, usaremos esta opción para buscar el mejor modelo. No es la mejor opción. Pero no es tan mala.
8. **n_jobs**: Siempre -1, para que use todos los cores presentes en 9. **max_samples**: Fracción de los samples.

Finalmente nuestra función de optimización queda la siguiente forma:

In [18]:
def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 32)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 2000)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 200)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)

    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

    model.fit(Xi, y)

    return ganancia_prob(model.oob_decision_function_, y)

storage_name = "sqlite:///" + db_path + "optimization_rf.db"
study_name = "exp_401_random-forest-opt"

study = optuna.create_study(
    direction="maximize",
    study_name=study_name,
    storage=storage_name,
    load_if_exists=True,
)

[I 2026-08-31 19:40:31,778] A new study created in RDB with name: exp_401_random-forest-opt

In [19]:
study.optimize(objective, n_trials=100)

[I 2026-08-31 19:41:29,106] Trial 0 finished with value: 326205000.0 and parameters: {'max_depth': 29, 'min_samples_split': 1406, 'min_samples_leaf': 106, 'max_features': 0.6547101311340564}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:41:45,740] Trial 1 finished with value: 288392500.0 and parameters: {'max_depth': 5, 'min_samples_split': 1912, 'min_samples_leaf': 133, 'max_features': 0.4888266003530553}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:41:55,893] Trial 2 finished with value: 301042500.0 and parameters: {'max_depth': 9, 'min_samples_split': 965, 'min_samples_leaf': 152, 'max_features': 0.15458951824213432}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:42:20,099] Trial 3 finished with value: 323785000.0 and parameters: {'max_depth': 25, 'min_samples_split': 1235, 'min_samples_leaf': 82, 'max_features': 0.2954643379795959}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:42:33,698] Trial 4 finished with value: 259985000.0 and parameters: {'max_depth': 3, 'min_samples_split': 661, 'min_samples_leaf': 144, 'max_features': 0.6537658226219256}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:42:44,786] Trial 5 finished with value: 324582500.0 and parameters: {'max_depth': 11, 'min_samples_split': 390, 'min_samples_leaf': 162, 'max_features': 0.1470545214930288}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:43:13,498] Trial 6 finished with value: 312812500.0 and parameters: {'max_depth': 7, 'min_samples_split': 1231, 'min_samples_leaf': 64, 'max_features': 0.6577760600878351}. Best is trial 0 with value: 326205000.0.
[I 2026-08-31 19:43:43,183] Trial 7 finished with value: 342100000.0 and parameters: {'max_depth': 8, 'min_samples_split': 21, 'min_samples_leaf': 191, 'max_features': 0.5959080078688581}. Best is trial 7 with value: 342100000.0.
[I 2026-08-31 19:44:30,768] Trial 8 finished with value: 334400000.0 and parameters: {'max_depth': 32, 'min_samples_split': 49, 'min_samples_leaf': 141, 'max_features': 0.5763796426609357}. Best is trial 7 with value: 342100000.0.
[I 2026-08-31 19:45:16,697] Trial 9 finished with value: 316085000.0 and parameters: {'max_depth': 16, 'min_samples_split': 1598, 'min_samples_leaf': 91, 'max_features': 0.5996089688950886}. Best is trial 7 with value: 342100000.0.
[I 2026-08-31 19:45:55,936] Trial 10 finished with value: 294250000.0 and parameters: {'max_depth': 19, 'min_samples_split': 178, 'min_samples_leaf': 1, 'max_features': 0.3671267240174322}. Best is trial 7 with value: 342100000.0.
[I 2026-08-31 19:46:32,539] Trial 11 finished with value: 335995000.0 and parameters: {'max_depth': 21, 'min_samples_split': 26, 'min_samples_leaf': 188, 'max_features': 0.4815955254865696}. Best is trial 7 with value: 342100000.0.
[I 2026-08-31 19:47:06,340] Trial 12 finished with value: 337947500.0 and parameters: {'max_depth': 18, 'min_samples_split': 463, 'min_samples_leaf': 195, 'max_features': 0.458366665800943}. Best is trial 7 with value: 342100000.0.
[I 2026-08-31 19:47:40,794] Trial 13 finished with value: 343502500.0 and parameters: {'max_depth': 16, 'min_samples_split': 546, 'min_samples_leaf': 200, 'max_features': 0.48415059849110437}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:48:00,983] Trial 14 finished with value: 331402500.0 and parameters: {'max_depth': 13, 'min_samples_split': 793, 'min_samples_leaf': 199, 'max_features': 0.2927312379512515}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:48:40,101] Trial 15 finished with value: 334125000.0 and parameters: {'max_depth': 15, 'min_samples_split': 361, 'min_samples_leaf': 171, 'max_features': 0.5384496566363053}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:48:47,270] Trial 16 finished with value: 239552500.0 and parameters: {'max_depth': 2, 'min_samples_split': 613, 'min_samples_leaf': 173, 'max_features': 0.39794263676042285}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:49:14,636] Trial 17 finished with value: 337810000.0 and parameters: {'max_depth': 11, 'min_samples_split': 244, 'min_samples_leaf': 120, 'max_features': 0.40095196878930567}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:49:21,339] Trial 18 finished with value: 291802500.0 and parameters: {'max_depth': 25, 'min_samples_split': 889, 'min_samples_leaf': 179, 'max_features': 0.06561162838262952}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:49:46,553] Trial 19 finished with value: 329312500.0 and parameters: {'max_depth': 7, 'min_samples_split': 525, 'min_samples_leaf': 199, 'max_features': 0.5612975650051968}. Best is trial 13 with value: 343502500.0.
[I 2026-08-31 19:50:10,321] Trial 20 finished with value: 348645000.0 and parameters: {'max_depth': 22, 'min_samples_split': 201, 'min_samples_leaf': 162, 'max_features': 0.3079128455717306}. Best is trial 20 with value: 348645000.0.
[I 2026-08-31 19:50:29,998] Trial 21 finished with value: 336600000.0 and parameters: {'max_depth': 23, 'min_samples_split': 183, 'min_samples_leaf': 162, 'max_features': 0.262927762201732}. Best is trial 20 with value: 348645000.0.
[I 2026-08-31 19:50:46,658] Trial 22 finished with value: 330577500.0 and parameters: {'max_depth': 21, 'min_samples_split': 285, 'min_samples_leaf': 178, 'max_features': 0.22577404942886103}. Best is trial 20 with value: 348645000.0.
[I 2026-08-31 19:51:11,772] Trial 23 finished with value: 344712500.0 and parameters: {'max_depth': 15, 'min_samples_split': 19, 'min_samples_leaf': 158, 'max_features': 0.3480649430780914}. Best is trial 20 with value: 348645000.0.
[I 2026-08-31 19:51:37,923] Trial 24 finished with value: 332365000.0 and parameters: {'max_depth': 15, 'min_samples_split': 679, 'min_samples_leaf': 121, 'max_features': 0.3518060949845474}. Best is trial 20 with value: 348645000.0.
[I 2026-08-31 19:52:09,706] Trial 25 finished with value: 353732500.0 and parameters: {'max_depth': 18, 'min_samples_split': 482, 'min_samples_leaf': 152, 'max_features': 0.4267960026837606}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:52:36,746] Trial 26 finished with value: 337067500.0 and parameters: {'max_depth': 19, 'min_samples_split': 135, 'min_samples_leaf': 128, 'max_features': 0.349305915911283}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:53:09,461] Trial 27 finished with value: 349827500.0 and parameters: {'max_depth': 26, 'min_samples_split': 370, 'min_samples_leaf': 155, 'max_features': 0.42208944293409306}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:53:50,261] Trial 28 finished with value: 325490000.0 and parameters: {'max_depth': 28, 'min_samples_split': 793, 'min_samples_leaf': 29, 'max_features': 0.43043371998454316}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:54:08,883] Trial 29 finished with value: 332200000.0 and parameters: {'max_depth': 28, 'min_samples_split': 372, 'min_samples_leaf': 108, 'max_features': 0.21469041649467294}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:54:51,798] Trial 30 finished with value: 323317500.0 and parameters: {'max_depth': 25, 'min_samples_split': 1021, 'min_samples_leaf': 106, 'max_features': 0.5198165069910561}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:55:15,745] Trial 31 finished with value: 337012500.0 and parameters: {'max_depth': 22, 'min_samples_split': 290, 'min_samples_leaf': 152, 'max_features': 0.31227405341785675}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:55:47,277] Trial 32 finished with value: 334730000.0 and parameters: {'max_depth': 30, 'min_samples_split': 443, 'min_samples_leaf': 158, 'max_features': 0.41773049569380466}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:56:14,010] Trial 33 finished with value: 346692500.0 and parameters: {'max_depth': 24, 'min_samples_split': 156, 'min_samples_leaf': 139, 'max_features': 0.342083383282115}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:56:31,237] Trial 34 finished with value: 284185000.0 and parameters: {'max_depth': 26, 'min_samples_split': 1977, 'min_samples_leaf': 138, 'max_features': 0.2357533057156589}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:57:06,062] Trial 35 finished with value: 347050000.0 and parameters: {'max_depth': 23, 'min_samples_split': 153, 'min_samples_leaf': 146, 'max_features': 0.4431110954204996}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:57:40,689] Trial 36 finished with value: 341467500.0 and parameters: {'max_depth': 27, 'min_samples_split': 302, 'min_samples_leaf': 147, 'max_features': 0.4499110255073398}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:58:18,472] Trial 37 finished with value: 299832500.0 and parameters: {'max_depth': 21, 'min_samples_split': 1783, 'min_samples_leaf': 127, 'max_features': 0.5037711434251244}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:58:46,855] Trial 38 finished with value: 340312500.0 and parameters: {'max_depth': 30, 'min_samples_split': 538, 'min_samples_leaf': 166, 'max_features': 0.38300959315150956}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:59:43,926] Trial 39 finished with value: 335170000.0 and parameters: {'max_depth': 18, 'min_samples_split': 744, 'min_samples_leaf': 87, 'max_features': 0.6935389829843943}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 19:59:55,998] Trial 40 finished with value: 297192500.0 and parameters: {'max_depth': 23, 'min_samples_split': 1019, 'min_samples_leaf': 108, 'max_features': 0.1545525676157959}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:00:21,645] Trial 41 finished with value: 341687500.0 and parameters: {'max_depth': 24, 'min_samples_split': 164, 'min_samples_leaf': 136, 'max_features': 0.326276892552534}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:00:43,231] Trial 42 finished with value: 332557500.0 and parameters: {'max_depth': 20, 'min_samples_split': 136, 'min_samples_leaf': 149, 'max_features': 0.284491707276051}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:01:16,061] Trial 43 finished with value: 337755000.0 and parameters: {'max_depth': 23, 'min_samples_split': 402, 'min_samples_leaf': 184, 'max_features': 0.44227579739226247}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:01:46,117] Trial 44 finished with value: 336902500.0 and parameters: {'max_depth': 26, 'min_samples_split': 97, 'min_samples_leaf': 143, 'max_features': 0.3831424984503959}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:02:23,506] Trial 45 finished with value: 339432500.0 and parameters: {'max_depth': 24, 'min_samples_split': 239, 'min_samples_leaf': 121, 'max_features': 0.4622229487851244}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:02:48,697] Trial 46 finished with value: 329972500.0 and parameters: {'max_depth': 17, 'min_samples_split': 505, 'min_samples_leaf': 132, 'max_features': 0.32652376950162565}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:03:03,631] Trial 47 finished with value: 328240000.0 and parameters: {'max_depth': 32, 'min_samples_split': 359, 'min_samples_leaf': 154, 'max_features': 0.19151598226054417}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:03:34,854] Trial 48 finished with value: 341302500.0 and parameters: {'max_depth': 20, 'min_samples_split': 237, 'min_samples_leaf': 168, 'max_features': 0.4153071377197284}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:03:56,098] Trial 49 finished with value: 327057500.0 and parameters: {'max_depth': 22, 'min_samples_split': 622, 'min_samples_leaf': 60, 'max_features': 0.2530316770332452}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:04:30,551] Trial 50 finished with value: 323345000.0 and parameters: {'max_depth': 29, 'min_samples_split': 1444, 'min_samples_leaf': 143, 'max_features': 0.47720508676102036}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:04:55,388] Trial 51 finished with value: 337535000.0 and parameters: {'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 158, 'max_features': 0.3542850125206642}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:05:20,863] Trial 52 finished with value: 337315000.0 and parameters: {'max_depth': 13, 'min_samples_split': 88, 'min_samples_leaf': 175, 'max_features': 0.3703741013368556}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:05:45,419] Trial 53 finished with value: 350405000.0 and parameters: {'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 163, 'max_features': 0.3255092806265945}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:06:06,871] Trial 54 finished with value: 343255000.0 and parameters: {'max_depth': 18, 'min_samples_split': 196, 'min_samples_leaf': 169, 'max_features': 0.2750529163338195}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:06:30,488] Trial 55 finished with value: 337287500.0 and parameters: {'max_depth': 20, 'min_samples_split': 342, 'min_samples_leaf': 185, 'max_features': 0.32037875144803374}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:07:00,776] Trial 56 finished with value: 331045000.0 and parameters: {'max_depth': 22, 'min_samples_split': 90, 'min_samples_leaf': 164, 'max_features': 0.401691092864468}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:07:23,612] Trial 57 finished with value: 329340000.0 and parameters: {'max_depth': 25, 'min_samples_split': 455, 'min_samples_leaf': 151, 'max_features': 0.3002064111436933}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:07:33,189] Trial 58 finished with value: 335912500.0 and parameters: {'max_depth': 17, 'min_samples_split': 205, 'min_samples_leaf': 116, 'max_features': 0.10972417664346382}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:08:16,135] Trial 59 finished with value: 340065000.0 and parameters: {'max_depth': 19, 'min_samples_split': 73, 'min_samples_leaf': 132, 'max_features': 0.5429447004505474}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:08:52,311] Trial 60 finished with value: 334015000.0 and parameters: {'max_depth': 24, 'min_samples_split': 274, 'min_samples_leaf': 99, 'max_features': 0.43523249528206653}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:09:17,518] Trial 61 finished with value: 333520000.0 and parameters: {'max_depth': 16, 'min_samples_split': 45, 'min_samples_leaf': 159, 'max_features': 0.33482120555552597}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:09:43,612] Trial 62 finished with value: 342237500.0 and parameters: {'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 141, 'max_features': 0.3823021264345839}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:10:09,411] Trial 63 finished with value: 332062500.0 and parameters: {'max_depth': 15, 'min_samples_split': 132, 'min_samples_leaf': 179, 'max_features': 0.35886210049144573}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:10:32,722] Trial 64 finished with value: 332860000.0 and parameters: {'max_depth': 27, 'min_samples_split': 178, 'min_samples_leaf': 156, 'max_features': 0.30427817337466184}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:10:55,741] Trial 65 finished with value: 336820000.0 and parameters: {'max_depth': 9, 'min_samples_split': 314, 'min_samples_leaf': 148, 'max_features': 0.4128603096842294}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:11:31,786] Trial 66 finished with value: 341797500.0 and parameters: {'max_depth': 17, 'min_samples_split': 427, 'min_samples_leaf': 161, 'max_features': 0.4683143911628086}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:11:51,804] Trial 67 finished with value: 333107500.0 and parameters: {'max_depth': 19, 'min_samples_split': 225, 'min_samples_leaf': 171, 'max_features': 0.2638662757049074}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:12:30,760] Trial 68 finished with value: 342292500.0 and parameters: {'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 127, 'max_features': 0.49476306737223674}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:12:56,451] Trial 69 finished with value: 334950000.0 and parameters: {'max_depth': 14, 'min_samples_split': 113, 'min_samples_leaf': 191, 'max_features': 0.3409477852598701}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:13:26,870] Trial 70 finished with value: 334977500.0 and parameters: {'max_depth': 26, 'min_samples_split': 581, 'min_samples_leaf': 135, 'max_features': 0.3881685073345512}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:13:58,269] Trial 71 finished with value: 340505000.0 and parameters: {'max_depth': 16, 'min_samples_split': 502, 'min_samples_leaf': 200, 'max_features': 0.4392855144632445}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:14:37,248] Trial 72 finished with value: 334620000.0 and parameters: {'max_depth': 21, 'min_samples_split': 673, 'min_samples_leaf': 179, 'max_features': 0.5071030544253619}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:15:11,643] Trial 73 finished with value: 342347500.0 and parameters: {'max_depth': 11, 'min_samples_split': 380, 'min_samples_leaf': 146, 'max_features': 0.5408584523311424}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:15:56,728] Trial 74 finished with value: 338222500.0 and parameters: {'max_depth': 16, 'min_samples_split': 293, 'min_samples_leaf': 164, 'max_features': 0.6042759043624054}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:16:24,234] Trial 75 finished with value: 329725000.0 and parameters: {'max_depth': 24, 'min_samples_split': 731, 'min_samples_leaf': 156, 'max_features': 0.36879210441676824}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:16:54,878] Trial 76 finished with value: 341137500.0 and parameters: {'max_depth': 18, 'min_samples_split': 575, 'min_samples_leaf': 184, 'max_features': 0.4252137115964019}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:17:23,987] Trial 77 finished with value: 335995000.0 and parameters: {'max_depth': 23, 'min_samples_split': 164, 'min_samples_leaf': 192, 'max_features': 0.39935875415536143}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:17:57,565] Trial 78 finished with value: 332777500.0 and parameters: {'max_depth': 14, 'min_samples_split': 876, 'min_samples_leaf': 151, 'max_features': 0.4766680863255897}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:18:30,975] Trial 79 finished with value: 337892500.0 and parameters: {'max_depth': 20, 'min_samples_split': 58, 'min_samples_leaf': 175, 'max_features': 0.4493945474047022}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:19:12,105] Trial 80 finished with value: 339075000.0 and parameters: {'max_depth': 27, 'min_samples_split': 256, 'min_samples_leaf': 140, 'max_features': 0.5202825396138544}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:19:27,373] Trial 81 finished with value: 332832500.0 and parameters: {'max_depth': 18, 'min_samples_split': 176, 'min_samples_leaf': 168, 'max_features': 0.1975981276454185}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:19:48,629] Trial 82 finished with value: 349360000.0 and parameters: {'max_depth': 17, 'min_samples_split': 338, 'min_samples_leaf': 170, 'max_features': 0.29034888003503784}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:20:06,945] Trial 83 finished with value: 332447500.0 and parameters: {'max_depth': 17, 'min_samples_split': 340, 'min_samples_leaf': 162, 'max_features': 0.24360930803428915}. Best is trial 25 with value: 353732500.0.
[I 2026-08-31 20:20:28,099] Trial 84 finished with value: 332997500.0 and parameters: {'max_depth': 15, 'min_samples_split': 430, 'min_samples_leaf': 153, 'max_features': 0.29082170177050864}. Best is trial 25 with value: 353732500.0.

Exploramos como fue la búsqueda de parámetros

In [20]:
optuna.visualization.plot_optimization_history(study)

In [21]:
plot_param_importances(study)

In [22]:
plot_slice(study)

In [23]:
plot_contour(study)

In [24]:
plot_contour(study, params=["max_depth", "min_samples_split"])

Ajustamos el mejor modelo a todo el conjunto de datos

In [25]:
model_rf = RandomForestClassifier(
        n_estimators=100,
        **study.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf.fit(Xi, y)

RandomForestClassifier(max_depth=18, max_features=0.4267960026837606,
                       max_samples=0.7, min_samples_leaf=152,
                       min_samples_split=482, n_jobs=-1, oob_score=True,
                       random_state=19828)

Guardamos el modelo, para no tener que optimizar cada vez que lo queramos usar.

In [26]:
filename = modelos_path + 'exp_206_random_forest_model_100.sav'
pickle.dump(model_rf, open(filename, 'wb'))

Y lo cargamos para utilizarlo

In [27]:
model_rf = pickle.load(open(filename, 'rb'))
model_rf

RandomForestClassifier(max_depth=18, max_features=0.4267960026837606,
                       max_samples=0.7, min_samples_leaf=152,
                       min_samples_split=482, n_jobs=-1, oob_score=True,
                       random_state=19828)

Ahora vamos medir su ganancia sobre el dataset de **Mayo**

In [28]:
y_pred_rf = model_rf.predict_proba(Xif)
ganancias_rf = ganancia_prob(y_pred_rf, y_futuro)
print(f"Ganancia de modelo RF: {ganancias_rf}")

Ganancia de modelo RF: 240790000.0

Frente a los 208.010.000 de mi mejor árbol es algo sustancialmente mejor.

Igualmente usamos poquitos estimadores. Tan solo unos 100. Suficientes como para que la optimización no tarde una eternidad, pero es muy poco. Deberíamos sumar unos cuantos más.

In [29]:
model_rf_1000 = RandomForestClassifier(
        n_estimators=1000,
        **study.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf_1000.fit(Xi, y)

filename_rf_1000 = modelos_path + 'exp_206_random_forest_model_1000.sav'
pickle.dump(model_rf, open(filename_rf_1000, 'wb'))

In [30]:
model_rf_1000 = pickle.load(open(filename_rf_1000, 'rb'))
model_rf_1000

RandomForestClassifier(max_depth=18, max_features=0.4267960026837606,
                       max_samples=0.7, min_samples_leaf=152,
                       min_samples_split=482, n_jobs=-1, oob_score=True,
                       random_state=19828)

Veamos si sumar 10 veces más estimadores tuvo algún efecto

In [31]:
y_pred_rf = model_rf_1000.predict_proba(Xif)
ganancias_rf = ganancia_prob(y_pred_rf, y_futuro)
print(f"Ganancia de modelo RF 1000: {ganancias_rf}")

Ganancia de modelo RF 1000: 240790000.0

Mejoró un poco! Cada peso vale.

Por último evaluamos cuales son las variables más importantes del modelo. ¿Habrá influido la imputación?

In [32]:
importances = model_rf.feature_importances_

features = X.columns
feat_importances = pd.DataFrame({'feature': features, 'importance': importances})
feat_importances = feat_importances.sort_values('importance', ascending=False)

feat_importances.head(25)

                         feature  importance
107                 ctrx_quarter    0.223544
22                mcuentas_saldo    0.084224
18                  mcaja_ahorro    0.079614
11               mpasivos_margen    0.069399
33         mprestamos_personales    0.065046
16             mcuenta_corriente    0.046558
28         mtarjeta_visa_consumo    0.032198
2                 active_quarter    0.031967
8           mrentabilidad_annual    0.031655
32         cprestamos_personales    0.027282
21      cdescubierto_preacordado    0.021245
72     mcomisiones_mantenimiento    0.020342
29               ctarjeta_master    0.019733
51                  cpayroll_trx    0.018525
26                 ctarjeta_visa    0.018017
12                    cproductos    0.017966
7                  mrentabilidad    0.014913
10               mactivos_margen    0.014696
52                      mpayroll    0.011723
9                    mcomisiones    0.010407
153             Visa_mpagominimo    0.010138
149               Visa_fechaalta    0.009944
138             Visa_msaldopesos    0.009900
27   ctarjeta_visa_transacciones    0.008895
127             Master_fechaalta    0.008883

Vamos a hacer un par de experimentos, que pasa si sacamos la variable más importante?

In [33]:
most_important_feature = feat_importances.iloc[0]['feature']

X_df = pd.DataFrame(Xi, columns=X.columns)
X_futuro_df = pd.DataFrame(Xif, columns=X_futuro.columns)

X_no_best_feature = X_df.drop(columns=[most_important_feature])
X_futuro_no_best_feature = X_futuro_df.drop(columns=[most_important_feature])

model_rf_no_best_feature = RandomForestClassifier(
    n_estimators=100,
    **study.best_params,
    max_samples=0.7,
    random_state=semillas[0],
    n_jobs=-1,
    oob_score=True
)

print(f"Entrenando modelo RF sin '{most_important_feature}'...")
model_rf_no_best_feature.fit(X_no_best_feature, y)

y_pred_rf_no_best_feature = model_rf_no_best_feature.predict_proba(X_futuro_no_best_feature)

ganancia_rf_no_best_feature = ganancia_prob(y_pred_rf_no_best_feature, y_futuro)

print(f"Ganancia del modelo RF sin '{most_important_feature}': {ganancia_rf_no_best_feature}")
print(f"Ganancia del modelo RF original: {ganancias_rf}")

Entrenando modelo RF sin 'ctrx_quarter'...
Ganancia del modelo RF sin 'ctrx_quarter': 251570000.0
Ganancia del modelo RF original: 240790000.0

¿Qué paso? ¿Se ha derrumbado las ganancias frente a la ausencia del pilar de los árboles?

Una prueba más, que pasa si sumamos variables que son ruido puro.

In [35]:
X_df_from_Xi = pd.DataFrame(Xi, columns=X.columns)

np.random.seed(semilla)

random_features_train = pd.DataFrame({
    f'random_feature_{i}': np.random.rand(len(X_df_from_Xi)) for i in range(1, 6)
})

X_with_random_features = pd.concat([X_df_from_Xi, random_features_train], axis=1)

model_rf_new_features = RandomForestClassifier(
    n_estimators=100,
    **study.best_params,
    max_samples=0.7,
    random_state=semillas[0],
    n_jobs=-1,
    oob_score=True
)

model_rf_new_features.fit(X_with_random_features, y)

importances_new_features = model_rf_new_features.feature_importances_

features_new_features = X_with_random_features.columns
feat_importances_new_features = pd.DataFrame({'feature': features_new_features, 'importance': importances_new_features})
feat_importances_new_features = feat_importances_new_features.sort_values('importance', ascending=False)

display(feat_importances_new_features.head(25))

                         feature  importance
107                 ctrx_quarter    0.222830
18                  mcaja_ahorro    0.089438
22                mcuentas_saldo    0.086300
11               mpasivos_margen    0.073710
33         mprestamos_personales    0.060474
16             mcuenta_corriente    0.040765
32         cprestamos_personales    0.034461
28         mtarjeta_visa_consumo    0.031662
8           mrentabilidad_annual    0.030532
29               ctarjeta_master    0.024558
2                 active_quarter    0.023399
12                    cproductos    0.020340
51                  cpayroll_trx    0.017851
21      cdescubierto_preacordado    0.017385
72     mcomisiones_mantenimiento    0.015724
7                  mrentabilidad    0.015608
26                 ctarjeta_visa    0.014347
10               mactivos_margen    0.012908
52                      mpayroll    0.012118
27   ctarjeta_visa_transacciones    0.011689
127             Master_fechaalta    0.011242
71     ccomisiones_mantenimiento    0.010101
153             Visa_mpagominimo    0.008420
149               Visa_fechaalta    0.007750
137             Visa_msaldototal    0.006888

Y una más, cual es el área bajo la curva en train?

In [36]:
from sklearn.metrics import roc_auc_score

y_pred_rf_train = model_rf_1000.predict_proba(Xi)

ganancia_rf_train = ganancia_prob(y_pred_rf_train, y)
print(f"Ganancia en el conjunto de entrenamiento: {ganancia_rf_train}")
print(f"Ganancia en el conjunto de Mayo: {ganancias_rf}")

y_train_numeric = (y == 'BAJA+2').astype(int)
y_futuro_numeric = (y_futuro == 'BAJA+2').astype(int)

auc_train = roc_auc_score(y_train_numeric, y_pred_rf_train[:, 1])
print(f"Área bajo la curva (AUC) en el conjunto de entrenamiento: {auc_train}")

auc_mayo = roc_auc_score(y_futuro_numeric, y_pred_rf[:, 1])
print(f"Área bajo la curva (AUC) en el conjunto de Mayo: {auc_mayo}")

Ganancia en el conjunto de entrenamiento: 425590000.0
Ganancia en el conjunto de Mayo: 240790000.0
Área bajo la curva (AUC) en el conjunto de entrenamiento: 0.9420289793544935
Área bajo la curva (AUC) en el conjunto de Mayo: 0.8839934848166041

Cuanta diferencia entre conjuntos. Seguramente debemos descartar este algoritmo, ¿o no?

Pregunta:
* **¿Cómo sabe que un random forest es superior a otro?**
* **¿Cómo supera el random forest presentado?**

## Tarea:

* Mejore la parametrización del **rf**